## Github workflow to create and upload github releases
name: Docker Image
description: "Create Docker Image"
branding:
  icon: "archive"
  color: "gray-dark"

inputs:
  tag:
    description: "Version tag of release"
    required: true
  docker_tag:
    description: "Version tag for docker images"
    required: true
  DOCKERHUB_USERNAME:
    description: "Docker username for publishing images"
    required: true
  DOCKERHUB_PASSWORD:
    description: "Docker password for publishing images"
    required: true

runs:
  using: "composite"
  steps:
    ## Setup Docker for the builds
    - name: Docker setup
      id: docker_setup
      uses: stacks-network/actions/docker@feat/release-signer-alongside-node
      with:
        username: ${{ inputs.DOCKERHUB_USERNAME }}
        password: ${{ inputs.DOCKERHUB_PASSWORD }}

    ## if the repo owner is not `stacks-network`, default to a docker-org of the repo owner (i.e. github user id)
    ## this allows forks to run the docker push workflows without having to hardcode a dockerhub org (but it does require docker hub user to match github username)
    - name: Set Local env vars
      id: set_env
      if: |
        github.repository_owner != 'stacks-network'
      shell: bash
      run: |
        echo "docker-org=${{ github.repository_owner }}" >> "$GITHUB_ENV"

    - name: Check Signer Release
      id: check_signer_release
      shell: bash
      run: |
        case "${{ inputs.tag }}" in
          signer-*)
            echo "is-signer-release=true" >> $GITHUB_ENV
            ;;
          *)
            echo "is-signer-release=false" >> $GITHUB_ENV
            ;;
        esac

    - name: Set Docker Tag RC Flag
      id: docker_tag_rc_flag
      shell: bash
      run: |
        if [[ "${{ inputs.docker_tag }}" =~ -rc[0-9]*$ ]]; then
          echo "docker_tag_rc=true" >> $GITHUB_ENV
        else
          echo "docker_tag_rc=false" >> $GITHUB_ENV
        fi

    ## Set docker metatdata
    ## - depending on the matrix.dist, different tags will be enabled
    ## ex. debian will have this tag: `type=ref,event=tag,enable=${{ matrix.dist == 'debian' }}`
    - name: Docker Metadata ( ${{matrix.dist}} )
      if: ${{ env.is-signer-release == 'true' }}
      id: docker_metadata_signer
      uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 #v5.5.1
      with:
        images: |
          ${{env.docker-org}}/stacks-signer
        tags: |
          type=raw,value=latest,enable=${{ inputs.docker_tag != '' && !env.docker_tag_rc && matrix.dist == 'debian' }}
          type=raw,value=${{ inputs.docker_tag }}-${{ matrix.dist }},enable=${{ inputs.docker_tag != '' && matrix.dist == 'debian'}}
          type=raw,value=${{ inputs.docker_tag }},enable=${{ inputs.docker_tag != '' && matrix.dist == 'debian' }}
          type=ref,event=tag,enable=${{ matrix.dist == 'debian' }}
          type=raw,value=latest-${{ matrix.dist }},enable=${{ inputs.docker_tag != '' && !env.docker_tag_rc && matrix.dist == 'alpine' }}
          type=raw,value=${{ inputs.docker_tag }}-${{ matrix.dist }},enable=${{ inputs.docker_tag != '' && matrix.dist == 'alpine' }}

    - name: Docker Metadata ( ${{matrix.dist}} )
      if: ${{ env.is-signer-release == 'false' }}
      id: docker_metadata_node
      uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 #v5.5.1
      with:
        ## tag images with current repo name `stacks-core` as well as legacy `stacks-blockchain`
        images: |
          ${{env.docker-org}}/${{ github.event.repository.name }}
          ${{env.docker-org}}/stacks-blockchain
        tags: |
          type=raw,value=latest,enable=${{ inputs.docker_tag != '' && !env.docker_tag_rc && matrix.dist == 'debian' }}
          type=raw,value=${{ inputs.docker_tag }}-${{ matrix.dist }},enable=${{ inputs.docker_tag != '' && matrix.dist == 'debian'}}
          type=raw,value=${{ inputs.docker_tag }},enable=${{ inputs.docker_tag != '' && matrix.dist == 'debian' }}
          type=ref,event=tag,enable=${{ matrix.dist == 'debian' }}
          type=raw,value=latest-${{ matrix.dist }},enable=${{ inputs.docker_tag != '' && !env.docker_tag_rc && matrix.dist == 'alpine' }}
          type=raw,value=${{ inputs.docker_tag }}-${{ matrix.dist }},enable=${{ inputs.docker_tag != '' && matrix.dist == 'alpine' }}

    ## Build docker image for signer release
    - name: Build and Push ( ${{matrix.dist}} )
      if: ${{ env.is-signer-release == 'true' }}
      id: docker_build_signer
      uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
      with:
        file: ./.github/actions/dockerfiles/Dockerfile.${{ matrix.dist }}-binary
        platforms: ${{ env.docker_platforms }}
        tags: ${{ steps.docker_metadata_signer.outputs.tags }}
        labels: ${{ steps.docker_metadata_signer.outputs.labels }}
        build-args: |
          TAG=${{ inputs.tag }}
          REPO=${{ github.repository_owner }}/${{ github.event.repository.name }}
          STACKS_NODE_VERSION=${{ inputs.tag || env.GITHUB_SHA_SHORT }}
          GIT_BRANCH=${{ env.GITHUB_REF_SHORT }}
          GIT_COMMIT=${{ env.GITHUB_SHA_SHORT }}
        push: ${{ env.DOCKER_PUSH }}

    ## Build docker image for node release
    - name: Build and Push ( ${{matrix.dist}} )
      if: ${{ env.is-signer-release == 'false' }}
      id: docker_build_node
      uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
      with:
        file: ./.github/actions/dockerfiles/Dockerfile.${{ matrix.dist }}-binary
        platforms: ${{ env.docker_platforms }}
        tags: ${{ steps.docker_metadata_node.outputs.tags }}
        labels: ${{ steps.docker_metadata_node.outputs.labels }}
        build-args: |
          TAG=${{ inputs.tag }}
          REPO=${{ github.repository_owner }}/${{ github.event.repository.name }}
          STACKS_NODE_VERSION=${{ inputs.tag || env.GITHUB_SHA_SHORT }}
          GIT_BRANCH=${{ env.GITHUB_REF_SHORT }}
          GIT_COMMIT=${{ env.GITHUB_SHA_SHORT }}
        push: ${{ env.DOCKER_PUSH }}