## Github workflow to create and upload a github release
name: Create Release
description: "Create GitHub Release"
branding:
  icon: "archive"
  color: "gray-dark"

inputs:
  tag:
    description: "Release Tag"
    required: true
  docker_tag:
    description: "Release Docker Tag"
    required: true
  GH_TOKEN:
    description: "GitHub Token"
    required: true

runs:
  using: "composite"
  steps:
    ## Downloads the artifacts built in `create-source-binary`
    - name: Download Artifacts
      id: download_artifacts
      uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
      with:
        pattern: ${{ inputs.docker_tag }}-binary-build-*
        path: release
        merge-multiple: true

    ## Generate a checksums file to be added to the release page
    - name: Generate Checksums
      id: generate_checksum
      uses: stacks-network/actions/generate-checksum@feat/release-signer-alongside-node
      with:
        artifact_download_pattern: "${{ inputs.docker_tag }}-binary-build-*"

    ## Upload the release archives with the checksums file
    - name: Upload Release
      id: upload_release
      uses: softprops/action-gh-release@69320dbe05506a9a39fc8ae11030b214ec2d1f87 #v2.0.5
      env:
        GITHUB_TOKEN: ${{ inputs.GH_TOKEN }}
      with:
        name: Release ${{ inputs.tag || github.ref }}
        tag_name: ${{ inputs.tag || github.ref }}
        draft: false
        prerelease: true
        fail_on_unmatched_files: true
        target_commitish: ${{ github.sha }}
        generate_release_notes: true
        files: |
          release/*.zip
          CHECKSUMS.txt
