name: "Generate and upload openAPI docs"
description: "Generate and upload openAPI docs"
branding:
  icon: "globe"
  color: "gray-dark"

inputs:
  output:
    description: "openAPI output file"
    required: false
    default: "./open-api-docs.html"
  input:
    description: "Input file to use to generate openAPI docs"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    ## checkout the code
    - name: Checkout the latest code
      id: git_checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    ## Use redoc to generate HTML of openapi.yml
    - name: Redoc
      id: run_redoc
      uses: seeebiii/redoc-cli-github-action@c9649b33918da5eb290b81cd03a943caea091540 # v10
      with:
        args: "bundle -o ${{ inputs.output }} ${{ inputs.input }}"

    ## Test the resultant html
    - name: check result
      id: check_redoc
      shell: bash
      run: |
        test -f ${{ inputs.output }} || (echo "Missing ${{ inputs.output }} from previous step." && exit 1)

    ## Upload the html file artifact
    - name: Upload bundled html
      id: upload_html_artifact
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: open-api-bundle
        path: |
          ${{ inputs.output }}
